// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtm30iaFIZXmUpmVnrl_BxtvDNloXoPSQ',
    appId: '1:730098671254:web:7e90eb995fc7a29556ecb7',
    messagingSenderId: '730098671254',
    projectId: 'listapp-2e415',
    authDomain: 'listapp-2e415.firebaseapp.com',
    storageBucket: 'listapp-2e415.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7G41obqlY7vWTGPTYDeohM5kVnzVtOoI',
    appId: '1:730098671254:android:490c918056ef75e156ecb7',
    messagingSenderId: '730098671254',
    projectId: 'listapp-2e415',
    storageBucket: 'listapp-2e415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3moJ2a8sPKG5DWGjZMounGdP9dJFq1nU',
    appId: '1:730098671254:ios:d173d8ef9666ac2456ecb7',
    messagingSenderId: '730098671254',
    projectId: 'listapp-2e415',
    storageBucket: 'listapp-2e415.appspot.com',
    iosBundleId: 'com.example.listapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3moJ2a8sPKG5DWGjZMounGdP9dJFq1nU',
    appId: '1:730098671254:ios:d173d8ef9666ac2456ecb7',
    messagingSenderId: '730098671254',
    projectId: 'listapp-2e415',
    storageBucket: 'listapp-2e415.appspot.com',
    iosBundleId: 'com.example.listapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtm30iaFIZXmUpmVnrl_BxtvDNloXoPSQ',
    appId: '1:730098671254:web:e6fc7a42dc14149256ecb7',
    messagingSenderId: '730098671254',
    projectId: 'listapp-2e415',
    authDomain: 'listapp-2e415.firebaseapp.com',
    storageBucket: 'listapp-2e415.appspot.com',
  );
}
